# action.yml
name: 'Publish'
description: 'Build and publish packages (fpm && packagecloud).'
inputs:
  command:
    description: 'command to execute'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
